name: Deploy Marimo Notebooks to GitHub Pages

on:
  push:
    branches: [ main ]  # Change this to your main branch name if different
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install marimo
        pip install pandas numpy matplotlib scikit-learn
        pip install -e .  # Install this project
    
    - name: Create output directory
      run: mkdir -p _site
    
    - name: Convert Marimo notebooks to HTML
      run: |
        for notebook in docs/*.py; do
          filename=$(basename -- "$notebook")
          filename_noext="${filename%.*}"
          echo "Converting $notebook to HTML..."
          marimo export html "$notebook" --output "_site/${filename_noext}.html"
        done
    
    - name: Create index page
      run: |
        echo "<html>
        <head>
          <title>Regressors - Documentation</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; max-width: 800px; margin: 0 auto; }
            h1 { color: #333; }
            ul { list-style-type: none; padding: 0; }
            li { margin-bottom: 10px; }
            a { color: #0366d6; text-decoration: none; }
            a:hover { text-decoration: underline; }
          </style>
        </head>
        <body>
          <h1>Regressors - Interactive Documentation</h1>
          <p>Welcome to the interactive documentation for the Regressors package. 
             These notebooks demonstrate how to use various regression models implemented in this package.</p>
          <h2>Available Notebooks:</h2>
          <ul>" > _site/index.html
        
        for notebook in docs/*.py; do
          filename=$(basename -- "$notebook")
          filename_noext="${filename%.*}"
          title=$(grep -m 1 -oP '(?<=# ).*' "$notebook" || echo "$filename_noext")
          echo "<li><a href=\"${filename_noext}.html\">$title</a></li>" >> _site/index.html
        done
        
        echo "</ul>
        <p><small>Generated on $(date) using <a href=\"https://marimo.io\">Marimo</a></small></p>
        </body>
        </html>" >> _site/index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true  # Use a clean branch each time 